name = "blazenote-frontend"
compatibility_date = "2025-10-21"
compatibility_flags = ["nodejs_compat"]
[[routes]]

pattern = "blazenote-frontend.enterprising-philosopher.sxplab.com"
custom_domain = true

[assets]
not_found_handling = "single-page-application"

[observability.logs]
enabled = true